### ISSUE TITLE
internet_identity fails to authenticate

### ISSUE THREAD

**Issue by carlek** [carlek/ii_integration#1]
I’m on a Mac with Apple Silicon and use the latest Chrome version, no vpn.  
After running the project locally:
```
import webbrowser as wb
f = open(".dfx/local/canister_ids.json")
d = json.load(f)
wb.open(f"http://127.0.0.1:4943/?canisterId={d['ii_integration_frontend']['local']}")
```
Click on Login. 
Follow steps on Internet Identity to create a new ID.

![image](https://github.com/carlek/ii_integration/assets/3924410/85abce16-98ee-4c57-9441-a126385b2ac7)

**Comment by frederikrothenberger** [comment]
Hi @carlek 

Our suspicion currently is that it is related to the latest dfx version and that only Apple Silicon is affected. Are you using dfx version 0.15.1? Could you try running this on dfx 0.14.4? (Note, this might entail _not_ using `dfx deps` but rather use a custom canister type with `candid` and `wasm` URLs, see example here: https://github.com/dfinity/internet-identity/blob/main/demos/using-dev-build/dfx.json)

Could you also please verify that indeed the latest dev build is running, by opening the chrome console and looking at the the version information.

**Comment by carlek** [comment]
@frederikrothenberger  
PROBLEM:  dfx 0.14.2 
SOLUTION: upgrade to 0.14.4 or 0.15.1

This problem happens with my setup (described above) on dfx 0.14.2
I upgraded to 0.14.4 and also ran a test on 0.15.1 and the problem does not occur.

Thanks for this suggestion:  I will use 0.15.1  at this point, until further notice.
